[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway.final"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/manager"
healthcheckTimeout = 300

[deploy.multiRegionConfig]
"us-east4-eqdc4a" = { numReplicas = 1 }
